fixtures:
  sysmlinks:
    bootstrap: "#{source_dir}"
  repositories:
    localrepo: "https://github.com/puppetlabs/pltraining-localrepo.git"
    pe_staging: "https://github.com/puppetlabs/puppetlabs-pe_staging.git"
    pe_repo: "https://github.com/puppetlabs/puppetlabs-pe_repo.git"
    dockeragent: "https://github.com/puppetlabs/pltraining-dockeragent.git"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.12.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "2.2.0"
    apache:
      repo: "puppetlabs/apache"
      ref: "1.10.0"
    wget:
      repo: 'maestrodev/wget'
      ref: '1.7.3'
    supervisord:
      repo: "ajcrowe/supervisord"
      ref: "0.6.1"
    epel:
      repo: "stahnma/epel"
      ref: "1.2.2"
    docker:
      repo: "garethr/docker"
    selinux:
      repo: "jfryman/selinux"
    dirtree:
      repo: "pltraining/dirtree"
    abalone:
      repo: "binford2k/abalone"
    userprefs:
      repo: "pltraining/userprefs"
    pe_gem:
      repo: "puppetlabs/pe_gem"
    network:
      repo: "razorsedge/network"
    staging:
      repo: "nanliu/staging"
    nginx:
      repo: "puppet/nginx"
      ref: "0.6.0"
    nodejs:
      repo: "puppet/nodejs"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
